name: A
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
  test:
    strategy:
      matrix:
        goarch: [ amd64, 386 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: go test ./...
        env:
          GOARCH: ${{ matrix.goarch }}
  build:
    strategy:
      matrix:
        goarch: [ amd64, 386, arm64, arm ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build ./...
        env:
          GOARCH: ${{ matrix.goarch }}
